#!/bin/bash

# 3-Clause BSD License
#
# Copyright (c) 2008-2026, James Philip Rowell,
# Alpha Eleven Incorporated
# www.alpha-eleven.com
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#  3. Neither the name of the copyright holder, "Alpha Eleven, Inc.",
#     nor the names of its contributors may be used to endorse or
#     promote products derived from this software without specific prior
#     written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# test_renumseq - Run the renumseq regression tests.

tmpArgs=/tmp/tmpARGS_RENUM.$$
tmpTestCmdFile=/tmp/tmpTESTCMDFILE_RENUM.$$
tmpFile=/tmp/tmpFILE_RENUM.$$
tmpLine=/tmp/tmpLINE_RENUM.$$
#
cleanupExit() {
    /bin/rm $tmpArgs > /dev/null 2>&1
    /bin/rm $tmpTestCmdFile > /dev/null 2>&1
    /bin/rm $tmpFile > /dev/null 2>&1
    /bin/rm $tmpLine > /dev/null 2>&1
    exit $1
}

trap cleanupExit INT

usage_exit() {
    echo "Usage: ${0##*/} [-h | --help] [--test-system-renumseq]"
    if [ "$1" = help ]; then
	cat - <<@eof

${0##*/} Run regression tests on renumseq. Must be run in the
<renumseq-repository>/tests directory.

Options:

 -h, --help         show this help and exit
 --test-system-renumseq run the regression tests on the version of
                    renumseq installed on the system. Output test
                    results to appropriatly named file.

@eof
        exit 0
    fi
    exit 1
}

TEST_SYSTEM_RENUMSEQ=no

#
# Parse options.
#
shopt -s extglob
while :
do
    case "$1" in
        -h|--help) usage_exit help
        ;;

        --test-system-renumseq) TEST_SYSTEM_RENUMSEQ=yes
             shift
        ;;

        --*|-*) usage_exit
        ;;

        *) break # We're done processing arguments, so let's get on with it. :-)
    esac
done

export LC_ALL=POSIX

# !!! This script MUST be run from the 'tests'
# !!! directory in the renumSeq git repo for this to work.
#
export TEST_DIR=`pwd`

if [[ `basename $TEST_DIR` != 'tests' ]]; then
    echo $0: error: not running from tests directory, aborted.
    cleanupExit 1
fi

export REPO_DIR=`dirname $TEST_DIR`

unalias lsseq > /dev/null 2>&1
unalias renumseq > /dev/null 2>&1
unalias rm > /dev/null 2>&1

TEST_OUT_FILENAME=test_renumseq.out.`uname`.new

if [ "$TEST_SYSTEM_RENUMSEQ" = no ]; then
    ln -sf ../renumseq/__main__.py  renumseq

    if [[ ! ":$PATH:" == *":$TEST_DIR:"* ]]; then
        export PATH="$TEST_DIR:$PATH"
    fi
else
    /bin/rm renumseq > /dev/null 2>&1 # In case softlink is in this dir.
    TEST_OUT_FILENAME=test_renumseq.out.`uname`.installed.new
fi

echo "Test is using " `which renumseq`

# Double check sensible REPO_DIR value before removing old testdir
#
if [ -z "$REPO_DIR" ]; then
    echo $0: error: REPO_DIR was empty, dangerous recursive rm avoided.
    cleanupExit 1
elif [[ "$REPO_DIR" == "/" ]]; then
    echo $0: error: REPO_DIR set to root, dangerous recursive rm avoided.
    cleanupExit 1
elif [[ `basename $REPO_DIR` != 'renumSeq' ]]; then
    echo $0: error: REPO_DIR might not be set to renumSeq repo, dangerous recursive rm avoided.
    cleanupExit 1
fi
rm -rf $REPO_DIR/tests/testdir/*

# Create list of test directories needed.
# Then touch the file names to make testfiles.
# Note: pwd should still be $TEST_DIR
# Note: This can create files and/or dirs with spaces in filenames
#
cat createTestData/create.?Test.files \
    | sed -e '/^[[:space:]]*$/d' \
    | sed -e '1,$ s/\/[^/]*$//' \
    | sort -u \
    | tr '\n' '\0' \
    > $tmpFile
cat $tmpFile | xargs -0 mkdir -p
#
cat createTestData/create.?Test.files \
    | sed -e '/^[[:space:]]*$/d' \
    | tr '\n' '\0' \
    > $tmpFile
cat $tmpFile | xargs -0 touch
cat $tmpFile | xargs -0 chmod 666

# Timestamp all the test files to be a fixed date so that their file times are 
# not dependent upon the date set when running the test. This gives us
# consistent test data output.
#
# Note: We use HAL's birthday from 2001: A Space Odyssey.
#
find testdir -type f -exec touch -t 199201121330 \{\} \;

# The following are tests. One test per line.
# The first item on a line is the directory relative to
#     $TEST_DIR/testdir to run the test in.
# The second is the command to run.
# The rest are args to the command.
# Note: use single quotes (') around args with spaces in the name
#
cat << EOF > $tmpTestCmdFile
.   uname
.   lsseq --version                         # Double check which version being used for this test.
.   lsseq -RPl --no-error-lists --show-bad-padding -m         # List all sequences in the testdir
.   renumseq                                # Run with no args - should do nothing
.   renumseq --version                      # MUST increment with each update/bug fix, corresp w/ release.
.   renumseq --help                         # To keep track of changes with help, plus check if correct
.   renumseq      null/foo.jpg              # No args - warning issued -> nothing to do.
.   renumseq -o 1 null/foo.jpg              # Not a sequence
.   renumseq -o 1 null/foo.[bar].jpg        # Not a sequence
.   renumseq -o 1 null/foo.[a-b].jpg        # Not a sequence
.   renumseq -o 1 null/foo.[-a-b].jpg       # Not a sequence
.   renumseq -o 1 null/foo.[-a--b].jpg      # Not a sequence
.   renumseq -o 1 null/foo.[xx-a-b].jpg     # Not a sequence
.   renumseq -o 1 c01/c.[011--003].jpg c02/c.[11-03].jpg  # Invalid range, [A-B] but A > B
.   renumseq -s -o 1 null/foo.jpg           # Repeat all those tests but silent
.   renumseq -s -o 1 null/foo.[bar].jpg     #    ditto
.   renumseq -s -o 1 null/foo.[a-b].jpg     #    ditto
.   renumseq -s -o 1 null/foo.[-a-b].jpg    #    ditto
.   renumseq -s -o 1 null/foo.[-a--b].jpg   #    ditto
.   renumseq -s -o 1 null/foo.[xx-a-b].jpg  #    ditto
.   renumseq -s -o 1 c01/c.[011--003].jpg c02/c.[11-03].jpg # ditto
a03 lsseq -RPl --no-error-lists --show-bad-padding -m       # Record sequence before renumbering
a03 renumseq -o 30 a.[0100-0110].jpg        # This should error out
a03 renumseq -s -o 30 a.[0100-0110].jpg     # Same with this, but silent.
a03 ls -o                                   # regular ls to see dates of files
a03 lsseq -RPl --no-error-lists --show-bad-padding -m       # Seq should be the same as above.
a03 renumseq -v -o 30 --force --touch 20010601-1230 a.[0100-0110].jpg # Now they should renumber.
a03 lsseq -RPl --no-error-lists --show-bad-padding -m       # Note new range.
a03 ls -o                                                   # Note that one files was not overwritten due to missing file in renumed seq
a02 ls -o                                                   # This next test was carefully laid out so that the highest x120 goes to x140
a02 lsseq -RPl --no-error-lists --show-bad-padding -m       # and the lowest x100 goes into the vacated x120 slot. Furthermore x105 is
a02 renumseq -v -o 20 --touch 20010601-1300 a.[0100-0120].jpg # missing leaving x0125 untouched after the renum.
a02 lsseq -RPl --no-error-lists --show-bad-padding -m       # Show new seq range.
a02 ls -o                                                   # Note all were renumbered EXCEPT x125
a01 ls -o                                                   # A list 100-140, 101 missing, 134-139 missing.
a01 lsseq -RPl --no-error-lists --show-bad-padding -m       # Move them all 100, so should leave 140 unmoved,
a01 renumseq -o 100 --touch 20010602 a.[0100-0133].jpg      # and 201 should be missing
a01 lsseq -RPl --no-error-lists --show-bad-padding -m       # and range should go up to 233. missing 141-199 also.
a01 ls -o
.   lsseq -RPl --no-error-lists --show-bad-padding -m b01 x01 y01
.   renumseq -v -o 100 b01/b.[555].jpg x01/x.[-11--03].jpg y01/y.[-011-0002].jpg
.   lsseq -RPl --no-error-lists --show-bad-padding -m b01 x01 y01
.   lsseq -RPl --no-error-lists --show-bad-padding -m a02
.   renumseq -v -o 10 a02/a.[0120-0140].jpg 
.   lsseq -RPl --no-error-lists --show-bad-padding -m a02
.   renumseq -v -o -10 a02/a.[0130-0150].jpg 
.   lsseq -RPl --no-error-lists --show-bad-padding -m a02
.   renumseq --verbose -o -1 --pad 3 a02/a.[0120-0140].jpg 
.   lsseq -RPl --no-error-lists --show-bad-padding -m a02
.   lsseq -RPl --no-error-lists --show-bad-padding -m d01
.   renumseq -v -o 20 /d01/d_[0100-0120].jpg
.   lsseq -RPl --no-error-lists --show-bad-padding -m d01
.   renumseq -v d01/d_[0120-0140].jpg
.   renumseq -v --replace-underscore d01/d_[0120-0140].jpg
.   lsseq -RPl --no-error-lists --show-bad-padding -m d01
e01 lsseq -RPl --no-error-lists --show-bad-padding -m
e01 renumseq -v --replace-underscore e_[5-9999].jpg
e01 lsseq -RPl --no-error-lists --show-bad-padding -m
.   renumseq -v --replace-underscore --pad 4 e02/e_[5-9999].jpg
.   renumseq -v --replace-underscore --pad 4 e03/e_[5-10005].jpg
.   lsseq -ZRPl d01
.   lsseq -ZRPl d02
.   renumseq -o 20 d02/d.[hi]_[0100-0120].jpg
.   lsseq -ZRPl d02
.   renumseq --replace-underscore d02/d.[hi]_[0120-0140].jpg
.   lsseq -ZRPl d02
.   lsseq -ZRPl f01
.   renumseq -v --pad 4 f01/f_[05-1005].jpg
g01 lsseq -n
g01 renumseq -v -o -400 g.[0530-0547].bgeo.gz
g01 lsseq -n
h01 ls -o
h01 renumseq --start 101 --touch xxxx h.[001-010].jpg
h01 renumseq --start 101 --touch 2010 h.[001-010].jpg
h01 renumseq --start 101 --touch 0101 h.[001-010].jpg
h01 renumseq --start 101 --touch 20100101 h.[001-010].jpg
h01 ls -o
h01 renumseq --start 1 --touch -- h.[101-110].jpg
h01 ls -o
h01 date
h01 echo The dates of the files in the last ls -o should match the prior date command.
h01 renumseq --foobar h.[001-010].jpg
h01 renumseq --start 101 --touch 20200631 h.[001-010].jpg
h01 renumseq --start 101 --touch 20200630 h.[001-010].jpg
h01 ls -o
h01 renumseq --start 1 --touch 200730 h.[101-110].jpg
h01 ls -o
i01 lsseq --no-error-lists
i01 renumseq --dry-run --start 100 --rename -- aaa.[1-10].jpg
i01 renumseq --dry-run --start 100 --rename aaa.[1-10].jpg
i01 renumseq --dry-run --start 100 --rename aaa.[1-10].jpg bbb.[1-10].jpg
i01 renumseq --dry-run --start 100 --rename xxx aaa.[1-10].jpg bbb.[1-10].jpg
i01 renumseq --pad 4 --dry-run --start 100 --rename xxx aaa.[1-10].jpg
i01 renumseq --pad 4          --start 100 --rename xxx aaa.[1-10].jpg
i01 renumseq --pad 3 --dry-run --start  20 --rename xxx ccc.[01-10].jpg
.   renumseq         -v --start 5 --rename g01/yyy i01/eee.[0001-0010].jpg
.   renumseq         -v --start 5 --rename yyy     i01/eee.[0001-0010].jpg
.   renumseq --pad 3 -v --start 5 --rename zzz     i01/ccc.[01-10].jpg
i01 renumseq --pad 3 -v --start 5 --rename nono    noSuchSeq.[01-10].jpg
.   renumseq --pad 3 -v --start 5 --rename nono    i01/noSuchSeq.[01-10].jpg
i01 lsseq --no-error-lists --only-sequences
i01 renumseq --pad 3 -v --start 50 --rename n.11.m_v001_   bbb.[1-10].jpg
i01 lsseq --no-error-lists --only-sequences
.   lsseq --prepend-path-rel --no-error-lists z01 'z 1' 'z 2'
EOF

export NUM_TESTS=`wc -l < $tmpTestCmdFile`

echo ------ Begin Tests ------ > $TEST_DIR/$TEST_OUT_FILENAME

# NOTE: We do not want globbing at all in renumseq tests since the tests
# use a lot of square brackets. No need to test other glob wildcards
# for renumseq as, say '*', is unlikely to be needed by the user
# since they need to fully specify the sequence being worked on
# so wildcards don't help.
#
# See test_lsseq in lsseq repo for how to allow globbing in test arguments.
# for test-code such as this.
#
set -f # Turn off globbing.
i=1
while true; do

    sed -n -e "$i p" $tmpTestCmdFile | sed -e 's/#.*//' > $tmpLine

    declare -a cmdLine=(`cat $tmpLine`)
    if [ ${#cmdLine[@]} -eq 0 ]; then
        break;
    fi

    # Note: Does not properly handle case when "workingDir" has spaces in the name.
    # Could be fixed, but for now just avoid doing tests with a "workingDir"
    # with spaces in the name.
    #
    workingDir=${cmdLine[0]}
    cmd=${cmdLine[1]}
    displayArgs=(${cmdLine[@]:2})

    # Strip out the first two words from $tmpLine to get the test args.
    # -E for extended regular expressions
    #
    sed -E 's/^[^[:space:]]+[[:space:]]+[^[:space:]]+[[:space:]]*//' < $tmpLine > $tmpArgs

    declare -a testArgs="($(< "$tmpArgs"))"

    echo "" >> $TEST_DIR/$TEST_OUT_FILENAME
    echo --- Test $i of $NUM_TESTS ---
    echo ----- Test $i -+- dir: $workingDir -+- $cmd ${displayArgs[@]} ----- >> $TEST_DIR/$TEST_OUT_FILENAME
    cd $TEST_DIR/testdir/$workingDir

    # Rewrite $tmpArgs with one arg per line.
    #
    cat /dev/null > $tmpArgs
    NUM_ELEMENTS=${#testArgs[@]}
    for (( elemIndex=0;elemIndex<$NUM_ELEMENTS;elemIndex++ )); do
        printf '%s\n' "${testArgs[${elemIndex}]}" >> $tmpArgs
    done

    # On Linux, use 'mapfile' to allow us to pass args with spaces in the names
    # to the test $cmd being run. Otherwise, on MacOS with only bash v3.x
    # (and no 'mapfile' command) use older technique.
    #
    if [ `uname` = Darwin ]; then
        MAPFILE=()
        while IFS= read -r line; do
            MAPFILE+=("$line")
        done < "$tmpArgs"
    else
        mapfile -t < "$tmpArgs"
    fi
    $cmd "${MAPFILE[@]}" >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "--+--  $cmd returned non-zero error code: $retVal  --+--" >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
    fi
    i=$((i + 1))
done
set +f # Turn globbing back on

sed -e "1,$ s-$TEST_DIR-/...absPathToRepo.../tests-g" < $TEST_DIR/$TEST_OUT_FILENAME | \
    sed -e "1,$ s/$USER/testUser/g" > $tmpFile
expand < $tmpFile | sed -e '1,$ s/ *$//' > $TEST_DIR/$TEST_OUT_FILENAME

cleanupExit 0
